Table users {
  id bigserial [pk]
  username varchar(50) [not null, unique]
  email varchar(100) [not null, unique]
  password varchar(255) [not null]
  full_name varchar(100)
  timezone varchar(50) [default: 'UTC']
  created_at timestamp [default: `CURRENT_TIMESTAMP`]
  updated_at timestamp [default: `CURRENT_TIMESTAMP`]
}

Table roles {
  id bigserial [pk]
  name varchar(30) [not null, unique]
}

Table user_roles {
  user_id bigint [ref: > users.id]
  role_id bigint [ref: > roles.id]
}

Table calendars {
  id bigserial [pk]
  user_id bigint [not null, ref: > users.id]
  name varchar(100) [not null]
  color varchar(20) [default: '#0099ff']
  is_default boolean [default: false]
  created_at timestamp [default: `CURRENT_TIMESTAMP`]
}

Table recurrences {
  id bigserial [pk]
  pattern varchar(20) [note: "DAILY, WEEKLY, MONTHLY, YEARLY"]
  interval integer [default: 1]
  end_date timestamp
  days_of_week varchar(50)
}

Table tasks {
  id bigserial [pk]
  calendar_id bigint [not null, ref: > calendars.id]
  title varchar(255) [not null]
  description text
  start_time timestamp
  end_time timestamp
  due_date timestamp
  all_day boolean [default: false]
  priority varchar(10) [default: 'MEDIUM', note: "LOW, MEDIUM, HIGH"]
  status varchar(20) [default: 'PENDING', note: "PENDING, IN_PROGRESS, COMPLETED, CANCELLED"]
  recurrence_id bigint [ref: > recurrences.id]
  created_at timestamp [default: `CURRENT_TIMESTAMP`]
  updated_at timestamp [default: `CURRENT_TIMESTAMP`]
}


Table reminders {
  id bigserial [pk]
  task_id bigint [ref: > tasks.id]
  reminder_time timestamp [not null]
  method varchar(20) [default: 'PUSH', note: "EMAIL, PUSH, SMS"]
  sent boolean [default: false]
}

Table shared_calendars {
  calendar_id bigint [ref: > calendars.id]
  shared_with_user_id bigint [ref: > users.id]
  permission_level varchar(20) [default: 'VIEW', note: "VIEW, EDIT, OWNER"]
}

